/**
 * Project Pragati - Translation strings (data-key → text per language)
 */

var TRANSLATIONS = {
  en: {
    home: 'Home',
    about: 'About Us',
    impact: 'Impact',
    sakhis: 'Sakhis',
    sponsor: 'Sponsor',
    bringToVillage: 'Bring to Village',
    sakhiLogin: 'Sakhi Login',
    getInvolved: 'Get Involved',
    heroTitle: 'Empowering Rural Women\nOne Entrepreneur at a Time',
    heroSubtitle: "A joint initiative by Shoolini University's Centre for Leadership Coaching and Shoolini Pehal Foundation, fostering self-reliance and sustainable growth.",
    learnMore: 'Learn More',
    ourMission: 'Our Mission',
    missionText: 'Project Pragati is dedicated to empowering rural women by providing them with the essential entrepreneurship training and support to establish and grow their own businesses. Our unique three-tier mentorship model connects participants (Sakhis) with personalized coaches (Sarthis) and student mentors (Sahyogis) to ensure comprehensive guidance, skill enhancement, and confidence-building for lasting success.',
    makingADifference: 'Making a Difference',
    makingADifferenceText: 'The first phase of Project Pragati has already shown inspiring results and transformative change.',
    villagesCovered: 'Villages Covered',
    womenEntrepreneurs: 'Women Entrepreneurs',
    trainingSessionsHeld: 'Training Sessions Held',
    firstPhaseCompleted: 'Completed & Equipped',
    meetTheSakhis: 'Meet the Sakhis',
    sakhi1Title: "A Sakhi's Voice",
    sakhi1Business: 'Handmade Crafts',
    sakhi1Quote: "Project Pragati didn't just teach me business skills; it gave me the courage to lead and inspire in my community.",
    sakhi2Title: "A Sakhi's Journey",
    sakhi2Business: 'Organic Spices',
    sakhi2Quote: "From my small kitchen to a growing business, I am now a self-reliant entrepreneur supporting my family's future.",
    sakhi3Title: "A Sakhi's Transformation",
    sakhi3Business: 'Tailoring & Design',
    sakhi3Quote: "The mentorship I received was life-changing. I have the confidence to manage my finances and grow my workshop.",
    ourTeam: 'Our Team',
    proChancellor: 'Pro-Chancellor, Shoolini University',
    viceChancellor: 'Vice-Chancellor & Programme Advisor, Shoolini University',
    headOfCentre: 'Assoc. Dir. & Head of Centre for Leadership Coaching, Shoolini University',
    chiefLearningOfficer: 'Chief Learning Officer',
    sponsorASakhi: 'Sponsor a Sakhi',
    sponsorIntro: 'Your sponsorship can transform lives by providing training, mentorship, and business setup support to rural women entrepreneurs.',
    sponsorOneSakhi: 'Sponsor One Sakhi',
    sponsorOneSakhiText: 'Support training, mentoring, and business setup for one rural woman entrepreneur. Help her build a sustainable livelihood and create lasting impact.',
    sponsorNow: 'Sponsor Now',
    sponsorVillageBatch: 'Sponsor a Village Batch',
    sponsorVillageBatchText: 'Support 10–15 women entrepreneurs from one village. Empower an entire community and create a ripple effect of economic growth and self-reliance.',
    sponsorBatch: 'Sponsor Batch',
    bringPragatiToVillage: 'Bring Pragati to My Village',
    villageFormIntro: 'Want to bring Project Pragati to your village? Fill out this form and our team will reach out to you to discuss the possibilities.',
    villageName: 'Village Name',
    panchayat: 'Panchayat',
    contactPerson: 'Contact Person',
    phone: 'Phone',
    womenInterested: 'Number of Women Interested',
    mainLivelihood: 'Main Livelihood Activity',
    submitRequest: 'Submit Request',
    joinUs: 'Join Us in Our Mission',
    joinUsText: 'Your support can make a real difference in the lives of these aspiring entrepreneurs. Choose how you want to contribute and become a part of their journey to self-reliance.',
    volunteer: 'Volunteer',
    volunteerText: 'Become a mentor (Sarthi) or a student mentor (Sahyogi) and share your expertise to guide our Sakhis on their entrepreneurial journey. Your time and knowledge are invaluable.',
    becomeAVolunteer: 'Become a Volunteer',
    donate: 'Donate',
    donateText: 'Your financial contribution can help us provide essential resources, training materials, and seed funding to our Sakhis, empowering them to build and scale their businesses.',
    donateNow: 'Donate Now',
    partnerWithUs: 'Partner with Us',
    partnerText: 'We welcome corporate and institutional partnerships to expand our reach and impact. Collaborate with us to create sustainable livelihoods and drive social change.',
    becomeAPartner: 'Become a Partner',
    loginIntro: 'Welcome back! Please login to access your dashboard.',
    sakhiId: 'Sakhi ID',
    password: 'Password',
    login: 'Login',
    welcomeSakhi: 'Welcome, Sakhi!',
    dashboardSubtitle: 'Track your progress, manage your products, and connect with your mentors.',
    myProducts: 'My Products',
    mySales: 'My Sales',
    trainingProgress: 'Training Progress',
    coachingSessions: 'Coaching Sessions',
    totalProducts: 'Total Products',
    productsActive: '5 active listings',
    totalSales: 'Total Sales',
    thisMonth: 'This month',
    customers: 'Customers',
    repeatCustomers: '8 repeat customers',
    businessBasics: 'Business Basics',
    financialLiteracy: 'Financial Literacy',
    digitalMarketing: 'Digital Marketing',
    upcomingSession: 'Upcoming Coaching Session',
    sessionWith: 'Session with:',
    sessionDate: 'Date:',
    sessionTime: 'Time:',
    sessionTopic: 'Topic:',
    businessGrowthStrategies: 'Business Growth Strategies'
  },
  hi: {
    home: 'होम',
    about: 'हमारे बारे में',
    impact: 'प्रभाव',
    sakhis: 'सखियाँ',
    sponsor: 'स्पॉन्सर',
    bringToVillage: 'गाँव में लाएँ',
    sakhiLogin: 'सखी लॉगिन',
    getInvolved: 'जुड़ें',
    heroTitle: 'ग्रामीण महिलाओं को सशक्त बनाना\nएक उद्यमी एक बार',
    heroSubtitle: 'शूलिनी विश्वविद्यालय के सेंटर फॉर लीडरशिप कोचिंग और शूलिनी पहल फाउंडेशन की संयुक्त पहल, आत्मनिर्भरता और सतत विकास को बढ़ावा देती है।',
    learnMore: 'और जानें',
    ourMission: 'हमारा मिशन',
    missionText: 'प्रोजेक्ट प्रगति ग्रामीण महिलाओं को उद्यमिता प्रशिक्षण और समर्थन प्रदान करके उन्हें सशक्त बनाने के लिए समर्पित है ताकि वे अपना व्यवसाय स्थापित कर सकें और बढ़ा सकें। हमारा अनूठा तीन-स्तरीय मेंटरशिप मॉडल प्रतिभागियों (सखियों) को कोच (सारथी) और छात्र मेंटर (सहयोगी) से जोड़ता है।',
    makingADifference: 'बदलाव लाना',
    makingADifferenceText: 'प्रोजेक्ट प्रगति के पहले चरण ने पहले ही प्रेरणादायक परिणाम दिखाए हैं।',
    villagesCovered: 'गाँव कवर',
    womenEntrepreneurs: 'महिला उद्यमी',
    trainingSessionsHeld: 'प्रशिक्षण सत्र',
    firstPhaseCompleted: 'पहला चरण पूर्ण',
    meetTheSakhis: 'सखियों से मिलें',
    sakhi1Title: 'एक सखी की आवाज़',
    sakhi1Business: 'हस्तनिर्मित क्राफ्ट',
    sakhi1Quote: 'प्रोजेक्ट प्रगति ने मुझे सिर्फ व्यवसाय कौशल नहीं सिखाया; इसने मुझे समुदाय में नेतृत्व करने का साहस दिया।',
    sakhi2Title: 'एक सखी की यात्रा',
    sakhi2Business: 'ऑर्गेनिक मसाले',
    sakhi2Quote: 'मेरी छोटी रसोई से बढ़ते व्यवसाय तक, मैं अब अपने परिवार के भविष्य का समर्थन करने वाली आत्मनिर्भर उद्यमी हूँ।',
    sakhi3Title: 'एक सखी का परिवर्तन',
    sakhi3Business: 'सिलाई और डिज़ाइन',
    sakhi3Quote: 'मुझे मिली मेंटरशिप जीवन बदलने वाली थी। मुझे अपने वित्त और कार्यशाला को बढ़ाने का आत्मविश्वास है।',
    ourTeam: 'हमारी टीम',
    proChancellor: 'प्रो-चांसलर, शूलिनी विश्वविद्यालय',
    viceChancellor: 'कुलपति और कार्यक्रम सलाहकार, शूलिनी विश्वविद्यालय',
    headOfCentre: 'सहायक निदेशक और सेंटर फॉर लीडरशिप कोचिंग के प्रमुख, शूलिनी विश्वविद्यालय',
    chiefLearningOfficer: 'मुख्य शिक्षण अधिकारी',
    sponsorASakhi: 'एक सखी को स्पॉन्सर करें',
    sponsorIntro: 'आपकी स्पॉन्सरशिप प्रशिक्षण, मेंटरशिप और व्यवसाय सेटअप के ज़रिए ग्रामीण महिला उद्यमियों की ज़िंदगियाँ बदल सकती है।',
    sponsorOneSakhi: 'एक सखी को स्पॉन्सर करें',
    sponsorOneSakhiText: 'एक ग्रामीण महिला उद्यमी के लिए प्रशिक्षण, मेंटरिंग और व्यवसाय सेटअप का समर्थन करें।',
    sponsorNow: 'अभी स्पॉन्सर करें',
    sponsorVillageBatch: 'गाँव बैच स्पॉन्सर करें',
    sponsorVillageBatchText: 'एक गाँव की 10–15 महिला उद्यमियों का समर्थन करें। पूरे समुदाय को सशक्त बनाएँ।',
    sponsorBatch: 'बैच स्पॉन्सर करें',
    bringPragatiToVillage: 'प्रगति को अपने गाँव लाएँ',
    villageFormIntro: 'प्रोजेक्ट प्रगति को अपने गाँव लाना चाहते हैं? यह फॉर्म भरें, हमारी टीम आपसे संपर्क करेगी।',
    villageName: 'गाँव का नाम',
    panchayat: 'पंचायत',
    contactPerson: 'संपर्क व्यक्ति',
    phone: 'फ़ोन',
    womenInterested: 'रुचि रखने वाली महिलाओं की संख्या',
    mainLivelihood: 'मुख्य आजीविका गतिविधि',
    submitRequest: 'अनुरोध भेजें',
    joinUs: 'हमारे मिशन में शामिल हों',
    joinUsText: 'आपका समर्थन इन उद्यमियों की ज़िंदगियों में वास्तविक बदलाव ला सकता है।',
    volunteer: 'स्वयंसेवक',
    volunteerText: 'मेंटर (सारथी) या छात्र मेंटर (सहयोगी) बनें और सखियों का मार्गदर्शन करें।',
    becomeAVolunteer: 'स्वयंसेवक बनें',
    donate: 'दान करें',
    donateText: 'आपका योगदान सखियों को संसाधन, प्रशिक्षण और बीज धन उपलब्ध कराने में मदद करता है।',
    donateNow: 'अभी दान करें',
    partnerWithUs: 'हमारे साथ साझेदारी',
    partnerText: 'हम कॉर्पोरेट और संस्थागत साझेदारी का स्वागत करते हैं।',
    becomeAPartner: 'साझेदार बनें',
    loginIntro: 'वापस स्वागत है! डैशबोर्ड एक्सेस करने के लिए लॉगिन करें।',
    sakhiId: 'सखी आईडी',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    welcomeSakhi: 'स्वागत है, सखी!',
    dashboardSubtitle: 'अपनी प्रगति देखें, उत्पाद प्रबंधित करें और मेंटर से जुड़ें।',
    myProducts: 'मेरे उत्पाद',
    mySales: 'मेरी बिक्री',
    trainingProgress: 'प्रशिक्षण प्रगति',
    coachingSessions: 'कोचिंग सत्र',
    totalProducts: 'कुल उत्पाद',
    productsActive: '5 सक्रिय लिस्टिंग',
    totalSales: 'कुल बिक्री',
    thisMonth: 'इस महीने',
    customers: 'ग्राहक',
    repeatCustomers: '8 नियमित ग्राहक',
    businessBasics: 'व्यवसाय मूल बातें',
    financialLiteracy: 'वित्तीय साक्षरता',
    digitalMarketing: 'डिजिटल मार्केटिंग',
    upcomingSession: 'आगामी कोचिंग सत्र',
    sessionWith: 'सत्र:',
    sessionDate: 'तारीख:',
    sessionTime: 'समय:',
    sessionTopic: 'विषय:',
    businessGrowthStrategies: 'व्यवसाय विकास रणनीतियाँ'
  }
};
